---
- name: Configure Network Services (NTP and Logging)
  hosts: all
  gather_facts: no

  tasks:
    - name: Configure NTP server
      cisco.ios.ios_config:
        lines:
          - ntp server time.google.com

    - name: Configure logging buffer size
      cisco.ios.ios_config:
        lines:
          - logging buffered 16384
